name: Wool & Wood API Tests and Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testsuite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Coding Standards
        run: npx eslint src

      - name: Run Tests
        run: npm test
